---
name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
            sudo apt -y update
            sudo apt -y upgrade
            sudo apt -y install python3-pip
            pip3 install ansible ansible-lint

      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        run: ansible-playbook workspace.yml -i 'localhost ansible_connection=local,'
